"""
    Demonstration for RNA databases visualization.

    Assumes that the directory "data/formatted" contains formatted RNA
    structure data. This dataset can be generated by executing the
    script `demo/preprocessing.py`.
"""


from diurnal import database, family, structure, train, visualize
import diurnal.utils.rna_data as rna_data


_, b, p = rna_data.read_ct_file("data/archiveII/5s_Acanthamoeba-castellanii-1.ct")
potential_pairings = structure.Primary.to_matrix(b)
secondary = structure.Secondary.to_matrix(p)
print("Visualize the secondary structure of an RNA molecule.")
visualize.secondary_structure(secondary, b)
print("Visualize the full structure of an RNA molecule.")
visualize.potential_pairings(potential_pairings, b, secondary)

print("Visualize the secondary structures of RNA families.")
SIZE = 256
database.download("./data/", "archiveII")
database.format(
    "./data/archiveII",  # Directory of the raw data to format.
    f"./data/formatted_matrix_{SIZE}",  # Formatted data output directory.
    SIZE,  # Normalized size.
    structure.Primary.to_matrix,
    structure.Secondary.to_matrix,
    verbosity=2
)

for name in family.NAMES:
    set = train.load_families(f"./data/formatted_matrix_{SIZE}", name)
    if not set["output"]:
        continue
    visualize.secondary_structures_heatmap(
        set["output"],
        f"Aggregated secondary structures of family {name}"
    )
